name = "HeckeAlgebras"
uuid = "25fc7e47-cefb-4c25-b93f-cca8114538c3"
authors = ["Ulrich Thiel <thiel@mathematik.uni-kl.de>"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
